yc_bg=#191b1e
yc_bg_container=#2a2d31
yc_fg=#d3d9e2
yc_fg_dim=#bfc5cd
yc_primary=#d3d9e2
yc_primary_container=#292c32
yc_secondary=#d3d9e2
yc_tertiary=#d3d9e2
yc_outline=#525860
yc_outline_variant=#31373e
yc_error=#ffb4ab
