yc_bg=#131318
yc_bg_container=#1f1f25
yc_fg=#e4e1e9
yc_fg_dim=#c7c5d0
yc_primary=#bdc2ff
yc_primary_container=#3c4279
yc_secondary=#c4c4dd
yc_tertiary=#e7b9d6
yc_outline=#91909a
yc_outline_variant=#46464f
yc_error=#ffb4ab
